# Generated by Django 3.0.7 on 2020-06-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0003_auto_20200623_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(default='World', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
