# Generated by Django 3.0.7 on 2020-06-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0004_auto_20200623_1400'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='productCategories',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
    ]
